language: c++
compiler:
  - gcc
  - clang
before_install:
  - sudo pip install cpp-coveralls
script:
  - cmake -DCOVERAGE=true . && make && make test
after_success:
    - if [ "$CC" = "gcc" ]; then coveralls --exclude third-party --gcov-options '\-lp'; fi
